### ISSUE TITLE
Extension overwrites config param

### ISSUE THREAD

**Issue by matej21** [Kdyby/Monolog#10]
If I have config parameter value under the `monolog` key it is [overwritten](https://github.com/Kdyby/Monolog/blob/master/src/Kdyby/Monolog/DI/MonologExtension.php#L49) by the extension

```neon
parameters:
    monolog:
         foo: bar
```

**Comment by fprochazka** [comment]
Hmm, simple change to this should solve it, right?

```php
$builder->parameters[$this->name]['name'] = $config['name'];
```

**Comment by matej21** [comment]
I think, it should not rewrite `monolog.name` parameter if there is one. Also, there might be e.g. string in the `monolog` parameter :) .. maybe this could work:
```php
DI\Config\Helpers::merge(isset($builder->parameters[$this->name]) ? $builder->parameters[$this->name] : [], ['name' => $config['name']);
```

**Comment by fprochazka** [comment]
The original intention of the parameter was to provide a way to push the name as the default channel name to `Logger` and to `SyslogHandler`.
