### ISSUE TITLE
Should the TracyExceptionProcessor unset the exception from context?

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Monolog#15]
Ref https://github.com/Kdyby/Monolog/commit/f4a6b3a410090f38441523ca45d703b1caf44762#commitcomment-15975623 via @matej21 

With the unset, I wanned to prevent the spamming of the log with information that is already in the tracy. But it makes sense for tools like raven or newrelic to be able to process the exception info.

So... should we remove the unset?

**Comment by wodCZ** [comment]
:+1: for removing unset
