### ISSUE TITLE
Compatibility with PHP 5.3

### ISSUE THREAD

**Issue by tomec-martin** [Kdyby/Monolog#16]
Commit f4a6b3a breaks compatibility with PHP5.3 (at least short arrays in MonologExtension.php). In readme you declare compatibility with PHP5.3. Is it still true?

**Comment by fprochazka** [comment]
That was definitely not intentional.

**Comment by fprochazka** [comment]
Yesterday I've spent about a hour tryting to get the PHP 5.3 compile in docker and it kept failing on some openssl errors.
I know Nette 2.3 supports PHP 5.3, but this is too much of a hassle for me at this moment.
If your company cannot upgrade to newer PHP, I'm open to fixing the compatibility, but not for free https://filip-prochazka.com/paid-support

Sorry, but I'm dropping the support for PHP 5.3 for now.

**Comment by tomec-martin** [comment]
It makes sense to drop support for historic versions of PHP :-)
Only for record for others - last version which supports PHP 5.3 is v1.1.0

**Comment by fprochazka** [comment]
@tomec-martin thank you for understanding :)
